spring:
  application:
    name: dubbo-registry-zookeeper-consumer-sample
demo:
  service:
    version: 1.0.0
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
server:
  port: 8090